## Source system wide properties
for SYSTEM_FILE in $HOME/.dotfiles/system/*; do
	. $SYSTEM_FILE
done


## ZSH - Plugins
plugins=(git)


## ZSH - Theme
ZSH_THEME="agnoster"
source $ZSH/oh-my-zsh.sh


## Load applications into path
# nvm
if [ -s $NVM_DIR/nvm.sh ]; then
	. $NVM_DIR/nvm.sh
fi
